### ISSUE TITLE
这个sdio有demo吗？

### ISSUE THREAD

**Issue by e190** [RT-Thread-packages/stm32_sdio#10]
我想用你这个sdio驱动配合 rtthread的SD驱动来使用SD卡，但是没找到你这个怎么使用的？

**Comment by enkiller** [comment]
# 一共三个步骤

## 准备阶段

需要准备下面四个东西

- 1 SDIO外设 首地址
- 2 SDIO外设 时钟速率
- 3 DMA发送函数
- 4 DMA接收函数

## 创建设备阶段

调用 `struct rt_mmcsd_host *sdio_host_create(struct stm32_sdio_des *sdio_des)` ，将上面四个东西配置进去

## 处理中断

在SDIO中断函数中，调用 `void rthw_sdio_irq_process(struct rt_mmcsd_host *host)` 处理中断

**Comment by e190** [comment]
目前DMA发送函数、接收函数就不知道怎么搞，首先没有DMA的驱动，我本想去看看 串口驱动中使用DMA的情况，才发现 用HAL库的bsp里串口驱动没有加DMA。现在该怎么办呢？
