### ISSUE TITLE
希望能够出一个适合STM32F103的，F1和F2的区别还是挺大的

### ISSUE THREAD

**Issue by master777895** [RT-Thread-packages/stm32_sdio#14]
希望能够出一个适合STM32F103的，F1和F2的区别还是挺大的

**Comment by master777895** [comment]
是F1和F4的差距大（刚刚打错了）

**Comment by enkiller** [comment]
https://github.com/RT-Thread/rt-thread/blob/master/bsp/stm32/libraries/HAL_Drivers/drv_sdio.c
